name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}
  SECRET: ${{ secrets.TEST_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps: # added
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
    - name: Echo Secret
      run: echo ${{ secrets.TEST_SECRET}}